const car = [
  {
    id: 1,
    title: 'Motif Jlamprang Pekalongan',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://koleksibajulengkap.com/wp-content/uploads/2016/08/Motif-Jlamprang-Pekalongan-Terbaik.jpg',
    description: 'catton 100%, pewarnaan teknik tulis asli',
    price: '1.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 2,
    title: 'Motif Liong',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://koleksibajulengkap.com/wp-content/uploads/2016/08/Model-Kain-Batik-Pekalongan-Motif-Liong.png',
    description: 'bahan katun 100% bukan cap, pewarnaan ATBM tulis asli',
    price: '1.200.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 3,
    title: 'Motif Semen',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://koleksibajulengkap.com/wp-content/uploads/2016/08/Batik-Pekalongan-Motif-Semen.jpg',
    description: 'bahan katun 100%, pewarnaan CAP asli',
    price: '2.000.000',
    owner: 'Supardi',
    rating: 3,
  },

]

const motorcycle = [
  {
    id: 1,
    title: 'Motif Sido Asih',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://moondoggiesmusic.com/wp-content/uploads/2018/09/Motif-Batik-SidoAsih.jpg',
    description: 'bahan katun 100% bukan ATBM',
    price: '100.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 2,
    title: 'Motif Kawung',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://moondoggiesmusic.com/wp-content/uploads/2018/09/Motif-Batik-Kawung.jpg',
    description: 'catton 100%, pewarnaan sablon printing',
    price: '90.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 3,
    title: 'Motif Mega Mendung',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://moondoggiesmusic.com/wp-content/uploads/2018/09/Motif-Batik-Mega-Mendung.jpg',
    description: 'bahan katun 100% original teknik cap khas cirebon',
    price: '250.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 4,
    title: 'Motif Sekar Jagad',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://moondoggiesmusic.com/wp-content/uploads/2018/09/Motif-Batik-Sekar-Jagad.jpg',
    description: 'bahan katun 100% pembuatan teknik sablon bukan ATBM',
    price: '80.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 5,
    title: 'Motif Sido Luhur',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://moondoggiesmusic.com/wp-content/uploads/2018/09/Batik-Sido-Luhur.jpg',
    description: 'catton 100% dengan teknik pewarnaan cap ',
    price: '90.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 6,
    title: 'Motif Tambal',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://moondoggiesmusic.com/wp-content/uploads/2018/09/Motif-Batik-Tambal.jpg',
    description: 'bahan katun 100% asli, motif kombinasi beberapa motif',
    price: '50.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 7,
    title: 'Motif Ceplok',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://moondoggiesmusic.com/wp-content/uploads/2018/09/Motif-Batik-Ceplok.jpg',
    description: 'katun 100% teknik pewarnaan printing bukan ATBM',
    price: '60.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 8,
    title: 'Motif Cuwiri',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://moondoggiesmusic.com/wp-content/uploads/2018/09/Batik-Cuwiri.jpg',
    description: 'katun 100% teknik pembuatan sablon.',
    price: '90.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 9,
    title: 'Motif Keraton',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://moondoggiesmusic.com/wp-content/uploads/2018/09/Motif-Batik-Keraton-1.jpg',
    description: 'bahan katun 100% dengan teknik pembuatan cap',
    price: '100.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 10,
    title: 'Motif Loreng',
    subtitle: 'Budaya Batik Indonesia',
    imageUrl: 'https://moondoggiesmusic.com/wp-content/uploads/2018/09/Batik-Loreng.jpg',
    description: 'katun 100% dengan pewarnaan printing bukan ATBM',
    price: '50.000',
    owner: 'Supardi',
    rating: 3,
  },
]


export { car, motorcycle }