const car = [
  {
    id: 1,
    title: 'Motif Jlamprang Pekalongan',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://koleksibajulengkap.com/wp-content/uploads/2016/08/Motif-Jlamprang-Pekalongan-Terbaik.jpg',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 2,
    title: 'Motif Liong',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://koleksibajulengkap.com/wp-content/uploads/2016/08/Model-Kain-Batik-Pekalongan-Motif-Liong.png',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 3,
    title: 'Motif Semen',
    subtitle: 'Honda Jazz 2015 - Yogyakarta',
    imageUrl: 'https://koleksibajulengkap.com/wp-content/uploads/2016/08/Batik-Pekalongan-Motif-Semen.jpg',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000',
    owner: 'Supardi',
    rating: 3,
  },

]

const motorcycle = [
  {
    id: 1,
    title: 'Motor Bekas - murah',
    subtitle: 'Motor Bekas - murah - Yogyakarta',
    imageUrl: 'https://www.designboom.com/wp-content/uploads/2017/07/classified-moto-frank-custom-triumph-speed-triple-3-motorcycle-designboom-500.jpg',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 2,
    title: 'Yamaha Xabre - 2016',
    subtitle: 'Yamaha Xabre - 2016 - Yogyakarta',
    imageUrl: 'https://s-media-cache-ak0.pinimg.com/originals/c2/da/05/c2da05694fcb2d6f49c95044f94fbe17.jpg',
    description: 'Di Yamaha Xabre - 2016 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 3,
    title: 'Motor Bekas - murah',
    subtitle: 'Motor Bekas - murah - Yogyakarta',
    imageUrl: 'https://www.designboom.com/wp-content/uploads/2017/07/classified-moto-frank-custom-triumph-speed-triple-3-motorcycle-designboom-500.jpg',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 4,
    title: 'Yamaha Xabre - 2016',
    subtitle: 'Yamaha Xabre - 2016 - Yogyakarta',
    imageUrl: 'https://s-media-cache-ak0.pinimg.com/originals/c2/da/05/c2da05694fcb2d6f49c95044f94fbe17.jpg',
    description: 'Di Yamaha Xabre - 2016 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 5,
    title: 'Motor Bekas - murah',
    subtitle: 'Motor Bekas - murah - Yogyakarta',
    imageUrl: 'https://www.designboom.com/wp-content/uploads/2017/07/classified-moto-frank-custom-triumph-speed-triple-3-motorcycle-designboom-500.jpg',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 6,
    title: 'Yamaha Xabre - 2016',
    subtitle: 'Yamaha Xabre - 2016 - Yogyakarta',
    imageUrl: 'https://s-media-cache-ak0.pinimg.com/originals/c2/da/05/c2da05694fcb2d6f49c95044f94fbe17.jpg',
    description: 'Di Yamaha Xabre - 2016 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 7,
    title: 'Motor Bekas - murah',
    subtitle: 'Motor Bekas - murah - Yogyakarta',
    imageUrl: 'https://www.designboom.com/wp-content/uploads/2017/07/classified-moto-frank-custom-triumph-speed-triple-3-motorcycle-designboom-500.jpg',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 8,
    title: 'Yamaha Xabre - 2016',
    subtitle: 'Yamaha Xabre - 2016 - Yogyakarta',
    imageUrl: 'https://s-media-cache-ak0.pinimg.com/originals/c2/da/05/c2da05694fcb2d6f49c95044f94fbe17.jpg',
    description: 'Di Yamaha Xabre - 2016 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 9,
    title: 'Motor Bekas - murah',
    subtitle: 'Motor Bekas - murah - Yogyakarta',
    imageUrl: 'https://www.designboom.com/wp-content/uploads/2017/07/classified-moto-frank-custom-triumph-speed-triple-3-motorcycle-designboom-500.jpg',
    description: 'Di jual Honda Jazz 2015 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
  {
    id: 10,
    title: 'Yamaha Xabre - 2016',
    subtitle: 'Yamaha Xabre - 2016 - Yogyakarta',
    imageUrl: 'https://s-media-cache-ak0.pinimg.com/originals/c2/da/05/c2da05694fcb2d6f49c95044f94fbe17.jpg',
    description: 'Di Yamaha Xabre - 2016 di area yogyakarta. Tanpa perantara dan tangan pertama. Masih mulus.',
    price: '125.000.000',
    owner: 'Supardi',
    rating: 3,
  },
]


export { car, motorcycle }